# Generated by Django 5.1 on 2024-09-30 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id_number', models.IntegerField(default=0)),
                ('author_user_varchar', models.CharField(max_length=200)),
                ('author_password_varchar', models.CharField(max_length=200)),
                ('author_pub_date_timestamp', models.DateTimeField(verbose_name='date published')),
                ('author_rol_varchar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_id_number', models.IntegerField(default=0)),
                ('articulo_titulo_varchar', models.CharField(max_length=200)),
                ('articulo_body_varchar', models.CharField(max_length=200)),
                ('articulo_pub_date_timestamp', models.DateTimeField(verbose_name='date published')),
                ('author_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogPost.autor')),
            ],
        ),
    ]
